// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    App: typeof import('./components/App.vue')['default']
    FileIcon: typeof import('./components/FileIcon.vue')['default']
    Status: typeof import('./components/Status.vue')['default']
    ToggleDark: typeof import('./components/ToggleDark.vue')['default']
    TopBar: typeof import('./components/TopBar.vue')['default']
  }
}
