/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./components/App.vue')['default']
    Editor: typeof import('./components/Editor.vue')['default']
    Explorer: typeof import('./components/Explorer.vue')['default']
    File: typeof import('./components/File.vue')['default']
    FileIcon: typeof import('./components/FileIcon.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    Information: typeof import('./components/Information.vue')['default']
    Loading: typeof import('./components/Loading.vue')['default']
    QuickOpen: typeof import('./components/QuickOpen.vue')['default']
    SplitPane: typeof import('./components/SplitPane.vue')['default']
    TextWithStops: typeof import('./components/TextWithStops.vue')['default']
  }
}
