// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    App: typeof import('./components/App.vue')['default']
    Editor: typeof import('./components/Editor.vue')['default']
    Explorer: typeof import('./components/Explorer.vue')['default']
    File: typeof import('./components/File.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    SplitPane: typeof import('./components/SplitPane.vue')['default']
  }
}
